services:
  - type: web
    name: VnContentGuard-Pro
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        scope: build
      - key: PYTHON_VERSION
        value: 3.11